<?php
    $category = $item->getCategories()->first();
    $bcr = array($item->getTitle() , $category->getTitle());
    $tmpcat = $category;
    //var_dump($tmpcat->getParent());exit;
    while($bc = $tmpcat->getParent()){
        array_push($bcr , $bc->getTitle());
        
        $tmpcat = $tmpcat->getParent();
    }
    $bcr = array_reverse($bcr);

?>
<section class="col-sm-12 col-xs-12 pp" id="Wrapper">
    
    <div class="col-md-12 col-xs-12">
        <ol class="breadcrumb pl0">
          <li><a href="#">Home</a></li>
          <?php foreach($bcr as $breadcrumb) :?>
          <li><a href="#"><?php echo $breadcrumb?></a></li>
          <?php endforeach;?>
        </ol>
    </div>
    
    <div class="col-md-12 col-xs-12">
        
        <div class="col-sm-4 col-xs-4 extended" >
            <div class="inner" style="min-height : 250px;border : 1px solid lightgray;">
                <div class="pr-display">
                    <img src="<?php echo $item->getCover()->getMedium(); ?>" 
                    alt="<?php echo $item->getTitle; ?>" width="100%" />
                </div>
            </div>
        </div>
        
        <div class="col-sm-8 col-xs-8">
            <div class="inner" style="min-height : 250px;border : 0px solid lightgray;">
                <h3 class="mt0 title">
                    <?php echo $item->getTitle();?> 
                    <small class="pull-right label label-warning"><?php echo substr($item->getGUID() ,0 , 10)?></small>
                </h3>
            </div>
            product content.
        </div>
        
    </div>
    
    <div class="" id="specifications">
            <h3 class="col-xs-12">Specifications</h3>
            
            <div class="col-md-6 col-xs-6 spc-wp">
                <div class="col-md-12 extended">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Audio</th   >
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            <tr>
                                <td>Iesire sunet (RMS):</td>
                                <td>2 x 10 W</td>
                            </tr>
                            <tr>
                                <td>Caracteristici superioare sunet:</td>
                                <td>Clear Phase Speaker
                                    S-Master
                                    Dolby Digital
                                    Dolby Digital Plus
                                    Dolby Digital Pulse
                                </td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
                
                <div class="col-md-12 extended">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Video</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            <tr>
                                <td>Iesire sunet (RMS):</td>
                                <td>2 x 10 W</td>
                            </tr>
                            <tr>
                                <td>Caracteristici superioare sunet:</td>
                                <td>Clear Phase Speaker
                                    S-Master
                                    Dolby Digital
                                    Dolby Digital Plus
                                    Dolby Digital Pulse
                                </td>
                            </tr>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            <tr>
                                <td>Iesire sunet (RMS):</td>
                                <td>2 x 10 W</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
                <div class="col-md-12 extended">
                     <table class="table">
                        <thead>
                            <tr>
                                <th>Video</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>
                
            </div>
            
            <div class="col-md-6 col-xs-6 spc-wp">
                
                <div class="col-md-12 extended">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Video</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            
                        </tbody>
                    </table>
                </div>

                <div class="col-md-12 extended">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Video</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            <tr>
                                <td>Iesire sunet (RMS):</td>
                                <td>2 x 10 W</td>
                            </tr>
                            <tr>
                                <td>Caracteristici superioare sunet:</td>
                                <td>Clear Phase Speaker
                                    S-Master
                                    Dolby Digital
                                    Dolby Digital Plus
                                    Dolby Digital Pulse
                                </td>
                            </tr>
                            <tr>
                                <td>Sistem audio:</td>
                                <td>NICAM/A2</td>
                            </tr>
                            <tr>
                                <td>Iesire sunet (RMS):</td>
                                <td>2 x 10 W</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                
            </div>
            
            <div class="clearfix"></div>
        </div>
    
    <div class="clearfix"></div>
    
</section>