
<header class="container-fluid">
    <a href="" class="logo" id="ML"><i class="fa fa-home"></i> TRIP</a>
    
    <ul class="navigation">
        <li>
            <a href=""><span class="iconb"><i class="fa fa-home"></i></span>Home</a>
        </li>
        <li>
            <a href=""><span class="iconb"><i class="fa fa-th-large"></i></span>Modules</a>
        </li>
        <li>
           <span class="dropdown" dropdown on-toggle="toggled(open)">
              <a href class="dropdown-toggle" dropdown-toggle>
                <i class="fa fa-th-large"></i></span>Modules
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="">Choice 1</a>
                </li>  
                <li>
                  <a href="">Choice 2</a>
                </li>  
                <li> 
                  <a href="">Choice 3</a>
                </li>
              </ul>
            </span>
        </li>
        
    </ul>
    
</header>

<div class="container-fluid content">
    <div ng:view class="viewport container-fluid"></div>    
</div>

<footer class="container-fluid">
    and footer
</footer>
    
<script src="<?php echo $this->basePath()?>/app/vendor/headjs-notify/src/load.js"   type="text/javascript" ></script>
<script src="<?php echo $this->basePath()?>/app/src/boot.js"                        type="text/javascript" ></script>

