
<header class="container-fluid">
    <a href="" class="logo" id="ML"><i class="fa fa-home"></i> TRIP</a>
    
    <ul class="navigation hidden-xs">
        <li>
            <span>
              <a href="#/home"><span class="iconb"><i class="fa fa-home"></i></span>Home</a>
            </span>
        </li>
        <li class="hide">
            <a href=""><span class="iconb"><i class="fa fa-th-large"></i></span>Modules</a>
        </li>
        <li>
           <span class="dropdown" dropdown on-toggle="toggled(open)">
              <a href class="dropdown-toggle" dropdown-toggle>
                <i class="fa fa-th-large"></i>Modules
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#/file-manager"><i class="fa fa-folder-o"></i>File Manger</a>
                </li>
                <li>
                  <a href="#/home"><i class="fa fa-gear"></i>System</a>
                </li>  
                <!--<li>-->
                <!--  <a href=""><i class="fa fa-laptop"></i>SEO</a>-->
                <!--</li>  -->
                <!--<li> -->
                <!--  <a href=""><i class="fa fa-th-large"></i>City Discover</a>-->
                <!--</li>-->
              </ul>
            </span>
        </li>
        <li>
           <span class="dropdown" dropdown on-toggle="toggled(open)">
              <a href class="dropdown-toggle" dropdown-toggle>
                <i class="fa fa-th-large"></i>Categories
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#/c/all"><i class="fa fa-list-ul"></i>List all</a>
                </li>  
                <li>
                  <a href="#/c/n"><i class="fa fa-sitemap"></i>Create</a>
                </li>  
                
              </ul>
            </span>
        </li>
        <li>
           <span class="dropdown" dropdown on-toggle="toggled(open)">
              <a href class="dropdown-toggle" dropdown-toggle>
                <i class="fa fa-desktop"></i>Products
              </a>
              <ul class="dropdown-menu">
                <li>
                  <a href="#/p/all"><i class="fa fa-list-ul"></i>List all</a>
                </li>  
                <li>
                  <a href="#/p/n"><i class="fa fa-sitemap"></i>Create</a>
                </li>  
                
              </ul>
            </span>
        </li>
        
    </ul>
    
</header>

<div class="container-fluid content">
    
    <div class="_ntf" ng-class="{show: notification}">Successfully saved.</div>
    
    <div ng:view class="viewport container-fluid"></div>    
</div>

<footer class="container-fluid">
    and footer
</footer>
    
<script src="<?php echo $this->basePath()?>/app/vendor/headjs-notify/src/load.js"   type="text/javascript" ></script>
<script src="<?php echo $this->basePath()?>/app/src/boot.js"                        type="text/javascript" ></script>

<?php $this->headLink()->prependStylesheet("app/vendor/elfinder-2.x/css/theme.css");?>
<?php $this->headLink()->prependStylesheet("app/vendor/elfinder-2.x/css/elfinder.full.css");?>
<?php $this->headLink()->prependStylesheet("//ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/smoothness/jquery-ui.css");?>
<!--<link rel="stylesheet" type="text/css" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/themes/smoothness/jquery-ui.css">-->