<?php
    $bcr = array($category->getTitle());
    $tmpcat = $category;
    //var_dump($tmpcat->getParent());exit;
    while($bc = $tmpcat->getParent()){
        array_push($bcr , $bc->getTitle());
        
        $tmpcat = $tmpcat->getParent();
    }
    $bcr = array_reverse($bcr);
    //var_dump($bcr);exit;
?>

<aside class="col-sm-3 col-xs-12 hide extended" id="SC">
    <div class="sc-inner">
        <div class='side-menu'>
            <header id="">
                 <i class="fa fa-align-justify"></i>
                 <h3>Categories</h3>
            </header>
            <section class="menu-content">
                    
                    <ul class="">
                        
                        <li>
                            <a class="has-many" href="">
                                <i class="fa fa-female mr5"></i>Woman
                            </a>
                            <div class="submenu" style="display : none;">
                                
                                <div class="submenu-inner col-sm-12">
                                    <?php for($subcat = 0 ; $subcat < 5 ; $subcat++) :?>
                                    <div class="col-sm-4 mt15 mb15">
                                        <h3 class="no-margin uppercase"><a href="">Handbags</a></h3>
                                        
                                        <ul>
                                            <li>
                                                <a href="">Fashion</a>
                                            </li>
                                            
                                            <li>
                                                <a href="">Hats and gloves</a>
                                            </li>
                                            
                                            <li>
                                                <a href="">Fashion</a>
                                            </li>
                                            
                                            <li>
                                                <a href="">Lifestyle</a>
                                            </li>
                                            
                                            <li>
                                                <a href="">Bras</a>
                                            </li>
                                            
                                            <li>
                                                <a href="">Sneakers</a>
                                            </li>
                                            
                                        </ul>
                                        
                                    </div>
                                    
                                    <?php endfor;?>
                                    
                                </div>
                                
                            </div>
                        </li>
                        
                        <li>
                            <a class="has-many" href="">
                                <i class="fa fa-male mr5"></i>Man
                            </a>
                        </li>
                        
                        <li>
                            <a class="has-many" href="">
                                <i class="fa fa-barcode mr5"></i>Fashion
                            </a>
                        </li>
                        
                        <li>
                            <a href="">
                                <i class="fa fa-black-tie mr5"></i>Accessories
                            </a>
                        </li>
                        
                    </ul>
                    
                </section>
        </div>
            
            
        <div class="widget mt35">
            
            <h2 class="title">
                <span class=""><?php echo $this->translate('Filters')?></span>
            </h2> 
                
            <content class="bordered">
                
                <?php foreach($filters as $filter) :?>
                <section class="col-md-12 filter-wp hide">
                    <h4><?php echo $filter->getTitle();?></h4>
                    <ul>
                        
                        <li>
                            <label>
                                <input type="checkbox" name="" class="" />
                                <span>XXL</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input type="checkbox" name="" class="" />
                                <span>XL</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input type="checkbox" name="" class="" />
                                <span>L</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input type="checkbox" name="" class="" />
                                <span>M</span>
                            </label>
                        </li>
                        <li>
                            <label>
                                <input type="checkbox" name="" class="" />
                                <span>S</span>
                            </label>
                        </li>
                        
                    </ul>
                    <hr class="separator" />
                </section>
                <?php endforeach;?>
                
                <span class="clearfix"></span>
            </content>
        </div>
            
    </div>
</aside>
    
    
<section class="col-sm-12 col-xs-12" id="Wrapper">
        
        <ol class="breadcrumb">
          <li><a href="#">Home</a></li>
          <?php foreach($bcr as $breadcrumb) :?>
          <li><a href="#"><?php echo $breadcrumb?></a></li>
          <?php endforeach;?>
        </ol>
        
        <div class="cat-cover">
            <?php if($category->getBanner()) :?>
            <img width=100% src="<?php echo $category->getBanner()->getHuge()?>" alt="<?php echo $category->getTitle();?>">
            <?php else : ?>
            
            <?php endif;?>
        </div>
        
        <h3 class="title"><?php echo $category->getTitle();?></h3>
        
        <div class="sort row">
            <div class="col-sm-6">
            
                <h5 style="display : inline; margin-right : 5px;">Sort by</h5>
                <select class="">
                    <option>--Select on option--</option>
                </select>
            </div>
            
            <div class="col-sm-6 text-right">
                <nav>
                  <ul class="pagination">
                    <li>
                      <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                      <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                  </ul>
                </nav>
            </div>
        </div>
        
        <hr class="separator" />
         
         
        <section class="prds row">
            <?php foreach($category->getItems() as $item) : ?>
            <div class="col-sm-4 product-wp">
                <div class="product-inner">
                    <span class="new-box box-label">New</span>
                    
                    <span class="sale-box box-label">Sale!</span>
                    
                    <div class="pr-img">
                        <img src="<?php echo $item->getCover()->getMedium() ;?>">
                    </div>
                    
                    <div class="pr-details">
                        <h5 class="product_name"> 
                            <a href="" title="Pilot Jacket"><?php echo $item->getTitle() ;?> </a>
                        </h5>
                        <div class="product-price-wp">
                            <span class="price">RON <?php echo $item->getProduct()->getPrice() ;?></span>
                            <!--<span class="old-price">RON 180</span>-->
                            <!--<span class="discount">-15%</span>-->
                        </div>
                    </div>
                    
                </div>
            </div>
            <?php endforeach; ?>
            <?php foreach($category->getItems() as $item) : ?>
            <div class="col-sm-4 product-wp">
                <div class="product-inner">
                    <span class="new-box box-label">New</span>
                    
                    <span class="sale-box box-label">Sale!</span>
                    
                    <div class="pr-img">
                        <img src="<?php echo $item->getCover()->getMedium() ;?>">
                    </div>
                    
                    <div class="pr-details">
                        <h5 class="product_name"> 
                            <a href="" title="Pilot Jacket"><?php echo $item->getTitle() ;?> </a>
                        </h5>
                        <div class="product-price-wp">
                            <span class="price">RON <?php echo $item->getProduct()->getPrice() ;?></span>
                            <!--<span class="old-price">RON 180</span>-->
                            <!--<span class="discount">-15%</span>-->
                        </div>
                    </div>
                    
                </div>
            </div>
            <?php endforeach; ?>
        </section>
        
</section>