<div class="row">

    <div class="col-md-3 extended">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
            <div class="_smh" style="border-radius: 5px;">
                <i class="fa fa-align-justify"></i> All Departments
            </div>
        </a>

        <ul class="dropdown-menu" id="SdMn">
            <li><a href="#">Computer Cases &amp; Accessories</a></li>
            <li><a href="#">CPUs, Processors</a></li>
            <li><a href="#">Fans, Heatsinks &amp; Cooling</a></li>
            <li><a href="#">Graphics, Video Cards</a></li>
            <li><a href="#">Interface, Add-On Cards</a></li>
            <li><a href="#">Laptop Replacement Parts</a></li>
            <li><a href="#">Memory (RAM)</a></li>
            <li><a href="#">Motherboards</a></li>
            <li><a href="#">Motherboard &amp; CPU Combos</a></li>
            <li><a href="#">Motherboard Components</a></li>
        </ul>


    </div>
    <div class="col-md-9 extended" id="BcR">
        <ul class="" >
            <li><a href="#">Computer Cases &amp; Accessories</a></li>
            <li><a href="#">CPUs, Processors</a></li>
            <li><a href="#">Fans, Heatsinks &amp; Cooling</a></li>
        </ul>
    </div>

</div>

<div class="row mt25">

    <div class="col-md-3 sidebar">
        <div class="widget">
            <h1>Product Filters</h1>
            <div class="body bordered">
                <?php for ($i = 5; $i < 10; $i ++) : ?>
                    <div class="category-filter filter">
                        <h2>Brands</h2>
                        <hr />
                        <ul>
                            <li>
                                <input class="custom-checkbox" id="ckb1" type="checkbox">
                                <label for="ckb1">Samsung</label> 
                                <span class="pull-right">(2)</span>
                            </li>
                            <li>
                                <input class="custom-checkbox" id="ckb2"  type="checkbox">
                                <label for="ckb2">Toshiba</label> 
                                <span class="pull-right">(2)</span>
                            </li>
                            <li>
                                <input class="custom-checkbox" id="ckb3"  type="checkbox">
                                <label for="ckb3">Alcatel</label> 
                                <span class="pull-right">(2)</span>
                            </li>
                            <li>
                                <input class="custom-checkbox" id="ckb4"  type="checkbox">
                                <label for="ckb4">Apple</label> 
                                <span class="pull-right">(2)</span>
                            </li>
                        </ul>
                        <hr />
                    </div><!-- /.category-filter -->
                <?php endfor; ?>
                <div class="price-filter mt10 filter">
                    <h2>Price</h2>
                    <hr>
                    <div class="price-range-holder">

                        <span class="min-max">
                            Price: $89 - $2899
                        </span>
<!--                        <span class="filter-button">
                            <a href="#">Filter</a>
                        </span>-->
                    </div>
                </div><!-- /.price-filter -->

            </div>
        </div>
    </div>

    <div class="col-md-9">

        <div class="control-bar col-md-12 ">
            <div class="col-md-3 extended custom-select">
                <select class="form-control">
                    <option value="1">24 per page</option>
                    <option value="2">48 per page</option>
                    <option value="3">32 per page</option>
                </select>
                <span></span>
            </div>
            <div class="col-md-4 pull-right display-toggler">
                <ul>
                    <li class="grid-list-button-item "><a data-toggle="tab" href="#grid-view"><i class="fa fa-th-large"></i> Grid</a></li>
                    <li class="grid-list-button-item active"><a data-toggle="tab" href="#list-view"><i class="fa fa-th-list"></i> List</a></li>
                </ul>
            </div>

        </div>
        <div class="clearfix"></div>

        <div class="tab-content">
            <div id="grid-view" class="products-grid fade tab-pane">
               <div class="pr-wp c-pr-wp">
                   <?php for($i = 0 ; $i < 8 ; $i++) :?>
                   <div class="col-sm-4 col-md-4 prd-hero extended">
                        <div class="_pr">
                            <div class="ribbon red"><span>sale</span></div>
                            <div class="image">
                                <img alt="" src="/public/assets/img/product-01.jpg">
                            </div>
                            <div class="body">
                                <div class="label-discount green">-50% sale</div>
                                <div class="title">
                                    <a href="index.php?page=single-product">VAIO Fit Laptop - Windows 8 SVF14322CXW</a>
                                </div>
                                <div class="brand">sony</div>
                            </div>
                            <div class="prices">
                                <div class="price-prev">$1399.00</div>
                                <div class="price-current pull-right">$1199.00</div>
                            </div>
                        </div>
                    </div>
                   <?php endfor;?>
                   <div class="clearfix"></div>
               </div>
                
            </div><!-- /.products-grid #grid-view -->

            <div id="list-view" class="products-grid fade tab-pane in active">
               
               <div class="pr-wp c-pr-wp">
                   
                   <?php foreach($this->category->getItems() as $item) :?>
                   <div class="col-sm-12 col-md-12 prd-hero extended list-item">
                        <div class="_pr list-item">
                            <div class="ribbon red"><span>sale</span></div>
                            
                            <div class="image col-md-3">
                                <?php 
                                    $coverEntity = $item->getCover();
                                    $cover = $coverEntity ? $coverEntity : null;
                                ?>
                                <img alt="" src="<?php if($cover) echo$cover->getSmall();?>">
                            </div>
                            
                            <div class="body col-md-6 no-margin pt5">
                                <div class="label-discount green">-50% sale</div>
                                <div class="title">
                                    <a href="<?php echo $this->url('item' , array( 'lang' => 'en' , 'slug' => $item->getSlug()));?>"><?php echo $item->getTitle();?></a>
                                </div>
                                <div class="brand">sony - <?php echo $item->getGUID();?></div>
                                <hr class="mt5 mb5" />
                                <p><?php echo $item->getDescription();?></p>
                                
                            </div>
                            
                            <div class="prices col-md-3">
                                <div class="price-current">$1199.00</div> 
                                <div class="price-prev mt10 mb10 block">$1399.00</div>
                                <button class="btn btn-danger btn-block">Add to cart</button>
                            </div>
                            
                            <div class="clearfix"></div>
                        </div>
                    </div>
                   <?php endforeach;?>
                   
               </div> 
               
                

            </div><!-- /.products-grid #list-view -->

        </div>
        <nav>
            <ul class="pagination products-pagination">
                <li class="disabled">
                  <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                  </a>
                </li>
                <li class="active">
                    <a href="#">1</a>
                </li>
               
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>

</div>