<div class="side-menu-inner">
    <nav>
        
        <ul>
            
            <li class="menu-item">
                <a href="">Home</a>
            </li>
            
            <li class="menu-item">
                <a href="">Fashion</a>
            </li>
            
            <li class="menu-item">
                <a href="">
                    Featured
                    <span> <i class="fa fa-angle-down pull-right mt10 mr10"></i> </span>
                </a>
                <div class="submenu-wp">
                    <ul class="submenu">
                        <li>
                            <a href="">Jackets</a>
                        </li>
                        <li>
                            <a href="">Coats</a>
                        </li>
                    </ul>
                </div>
                
            </li>
            
            <li class="menu-item">
                <a href="">Men</a>
            </li>
            
            <li class="menu-item">
                <a href="">Woman</a>
            </li>
            
            <li class="menu-item">
                <a href="">About</a>
            </li>
            
            
        </ul>
        
    </nav>
    
    
</div>