<div class="mt25"></div>
<div class="">
    <div class="col-xs-12">
        <div class="title has-button ">
            <h3 class="site-heading">
                <span>TRENDING THIS WEEK</span>
            </h3>
            <a class="site-button has-icon pull-right noright" href="">
                <i class="fa fa-th"></i>
                <span class="text">VIEW ALL PRODUCTS</span>
            </a>
        </div>
    </div>
</div>
<div class="products products-list mb50">
    
    <?php for($pr = 0 ; $pr < 3 ; $pr++) : ?>
        
        <div class="col-sm-4 col-xs-6 mb25 product-wp">
            <div class="prod-inner product">
                
                <div class="image-mask">
                    <img src="<?php echo $this->basePath('images/product-image.jpg')?>" alt="product image">
                </div>
                
                <div class="product-details">
                
                    <div class="col-xs-12">
                        <!--<div class="col-xs-12 col-sm-6">-->
                            <h3><a href="">Achilles Low</a></h3>
                            <span class="posted_in"><a href="" rel="tag">Footwear</a></span>
                            
                            <span class="pr-price">199.99 RON</span>
                            <span class="pr-stars">
                                <i class="fa fa-star on"></i>
                                <i class="fa fa-star on"></i>
                                <i class="fa fa-star on"></i>
                                <i class="fa fa-star on"></i>
                                <i class="fa fa-star off"></i>
                            </span>
                        <!--</div>-->
                        <!--<div class="col-xs-12 col-sm-6"></div>-->
                    </div>
                    
                    
                    <div class="clearfix"></div>
                </div>
                
            </div>
        </div>
        
    <?php endfor;?>
    
    
</div>