<div class="container-fluid stripe">
    
    <div class="col-md-12">
        
        <ul class="breadcrumb">
            
            <li> 
                <a href="">Home page</a> 
            </li>
            
            <!--<li> -->
            <!--    <i class="fa fa-home"></i>-->
            <!--</li>-->
            
            <li> 
                <a href="">Login</a> 
            </li>
            
        </ul>
        
    </div>
    
</div>

<div class="container-fluid mb30">
    <div class="col-md-12 push-up over-sld">
        
        <div class="col-md-7">
            <h3>My <strong>Account</strong></h3>    
            <hr />
            
            <h4>Login</h4>
            <h5>Email address *</h5>
            <input type="email" name="" class="form-control">
            <br />
            <h5>Password *</h5>
            <input type="password" name="" class="form-control">
            
        </div>
        
        <div class="col-md-5">
            <h3>Recent <strong>Reviews</strong></h3>    
            <hr />
        </div>
        
    </div>
    
    
</div>