
<div class="container-fluid stripe">
    
    <div class="container">
            
        <div class="col-md-12">
            
            <ul class="breadcrumb">
                
                <li> 
                    <a href="">Home page</a> 
                </li>
                
                <li> 
                    <a href="">Login</a> 
                </li>
                
            </ul>
            
        </div>
        
    </div>    
</div>


<div class="container">
    
    <div class="container-fluid mb30">
    
        <div class="col-md-12 push-up over-sld">
        
            <div class="col-md-7">
                <h3>My <strong>Account</strong></h3>    
                <hr />
                
                <h4>Login</h4>
                <h5><strong>Email address *</strong></h5>
                <input type="email" name="" class="form-control">
                <br />
                <h5><strong>Password *</strong></h5>
                <input type="password" name="" class="form-control">

                <br />
                
                <p class="col-md-12 extended">
                    <input type="submit" class="btn btn-primary" name="" value="Login">
                    <label for="rememberme" class="inline">
                    <input name="rememberme" type="checkbox" id="rememberme" value="forever"> Remember me	</label>
                </p>
                
                <p class="lost_password extended col-md-12">
                    <a href="https://demo.proteusthemes.com/webmarket/my-account/lost-password/">Lost your password?</a>
                </p>
                
            </div>
        
            <div class="col-md-5">
                <h3>Recent <strong>Reviews</strong></h3>    
                <hr />
            </div>
        
        </div>
    
    </div>    
    
</div>

