<form class="" method="POST" enctype="multipart/form-data">

        <div class="form-content col-md-12 extended">
            
            <legend><span>Edit product</span></legend>
            
            
            <div class="clearfix"></div>
            
            <div class="form-group col-md-12">
                
                <div class="col-md-3">
                    <label for="">Galery</label>    
                </div>
                <div class="col-md-9">
                    <input type="file" name="Galery[]" multiple="">
                    
                </div>
                
                <div class="col-md-12" id="Galery">
                    
                    <!--<div style="display : inline-block"></div>-->
                    
                </div>
                
                <input type="submit" />
                    
            </div>
            
            

        </div> <!-- END FORM CONTENT -->
        <div class="clearfix"></div>
    </form>