<div class="container">
    
    <div class="col-md-6">
        
        <div class="header-logo">
            <img height=70 src="<?php echo $this->basePath() . '/assets/img/logo__.png'?>" alt="" />    
        </div>
        
    </div>
    
    <div class="col-md-4">
        
        <div class="pt25 col-md-12 extended">
            <div class="col-md-8 text-right">
                <small class="uppercase">We are here to help you</small> <br/>
                <em class="lightgray-text">Lorem ipsum donect..</em>
            </div>
            <div class="col-md-4">
                <i class="fa fa-envelope-o large" style="font-size : 35px;"></i>
            </div>
            
        </div>
        
    </div>
    
    <div class="col-md-2 extended">
        
        <div class="pt25 col-md-12 extended">
            <div class="col-md-6 extended">
                <small class="uppercase block text-right pr15">My Cart <i class="fa fa-caret-down hide"></i></small> 
                <span class="uppercase gray-text text-right pr15 block"> $0.00 </span>
            </div>
            <div class="col-md-6 extended relative">
                
                <div class="shopping-bag">
                    <span>0</span>
                </div>
                
                <span class="pull-left ml10 mt10 gray-text"> <i class="fa fa-chevron-circle-down"></i> </span>
                
                <div class="open-cart">
                    <strong>Shopping Cart</strong>
                    
                    <?php for($i = 1 ; $i < 4 ; $i++) : ?>
                    <div class="small-cart-item">
                        <div class="col-md-4">
                            <img width="" src="<?php echo 'http://wp.wpusta.com/macromart/wp-content/uploads/2015/01/tshirt2-100x100.jpg'?>" alt="pr nm" />
                        </div>
                        <div class="col-md-8">
                            <p class="mt0 mb0">product name</p>
                            <p class="mt0 mb0 red-text">$0.00</p>
                            <p class="mt0 mb0"><strong>x 1</strong></p>
                        </div>
                        
                        
                        <div class="clearfix"></div>
                    </div>
                    <?php endfor;?>
                    
                    <div class="subtotal mt5">
                        <strong class="pull-left mt5">Subtotal:</strong>
                        <h3 class="red-text pull-right">$0.00</h3>
                        <div class="clearfix"></div>
                    </div>
                    
                    <div class="mt15 col-md-12 extended">
                        <button class="btn btn-primary block col-md-12">Checkout</button>
                    </div>
                    
                </div>
                
            </div>      
        </div>
    
    </div>
    
</div>