<div class="container">
    
    <div class="top-band col-md-12 extended">
        
        <div class="col-md-5 extended">
            <span> <i class="fa fa-mobile small"></i> &nbsp; Free shipping </span>    &nbsp; | &nbsp;
            <span>Phone : 0724 508 044</span> &nbsp; | &nbsp;
            <span>Hot Line : 055 500 050<span> 
        </div>
        
        <div class="col-md-5 pull-right extended relative text-right">
            <span class='lgn-hdl active'> Login / Sign Up </span>    &nbsp; | &nbsp;
            <span> <i class="fa fa-heart-o"></i> &nbsp; Wishlist</span> &nbsp; | &nbsp;
            <span class="social-media"> 
                <i class="fa fa-facebook small"></i>
                <i class="fa fa-twitter small"></i>
                <i class="fa fa-google-plus small"></i>
                <i class="fa fa-youtube-play small"></i> 
            </span> 
            
            <div class="opn-lgn">
                
                <form class="login-menu-form" action="" method="GET">
                    <div class="">
                        
                        <label class="uppercase">Username <span class="required">*</span></label>
                        
                        <input type="text" class="form-control" />
                        
                    </div>
                    
                    <div class="mt5">
                        
                        <label class="uppercase">Password <span class="required">*</span></label>
                        
                        <input type="text" class="form-control" />
                        
                    </div>
                    
                    <p class="required text-right mt5"> * Required</p>
                    
                    <div class="mt5">
                        <input type="submit" class="btn btn-primary" value="Login" />
                    </div>
                    
                    <div class="mt10">
                        <a href="#">Forgot your password?</a>
                    </div>
                    <div class="">
                    <span>New customer?</span> <a class="required" href="#">Sign up</a>    
                    </div>
                    
                </form>
                
            <div>
            
        </div>
        
        <div class="clearfix"></div>
    </div>
</div>