<div class="col-md-12 col-sm-12 extended navig">
    
    <div class="col-md-8 col-sm-8">
        
        <ul class="main-nav hidden-sm">
            <li>
                <a href=""> Home </a>
            </li>

            <li class="relative dropdown">
                
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Categories &nbsp; <i class="fa fa-caret-down"></i>
                </a>
                
                 <ul class="dropdown-menu">
                    <li class="col-md-12 extended">
                        <a href="#">Electronics</a>
                        </li>
                    <li class="col-md-12 extended">
                        <a href="#opening">Mobile</a>
                    </li>
                </ul>            
            </li>
            
            <li>
                <a href="">
                     Blog &nbsp; <i class="fa fa-caret-down"></i>
                </a>
            </li>
            
            <!--<li>-->
            <!--    <a href=""> -->
            <!--        Features &nbsp; <i class="fa fa-caret-down"></i>-->
            <!--    </a>-->
            <!--</li>-->
            
            <li>
                <a href=""> About Us </a>
            </li>
            
            <li>
                <a href=""> Contact </a>
            </li>
            
        </ul>
        
        <form class="pull-right hidden-sm relative search-form" action="" method="GET">
            <input type="text" class="form-control">
            <button><i class="fa fa-search"></i></button>
        </form>
        
        <div class="visible-sm col-md-12 extended">
            
            <button>
                <i class="fa fa-home large"></i>
            </button>
            
        </div>
        
    </div>
        
    <div class="col-md-4 col-sm-4">
        
        <div class="cart-container col-md-12 extended ">
        
            <div class="cart-wrp col-md-12 extended">
            
                <p class="items">CART <span class="dark-clr">(0)</span></p>
                <p class="dark-clr hidden-tablet"><span class="amount">$0.00</span></p>
                <a href="" class="btn btn-danger">
        				<i class="fa fa-shopping-cart"></i>
    			</a>
                
            </div>
            
            <div class="open-cart">
                
                <div class="item-in-cart clearfix">
				
    				<div class="image">
        				<a href="https://demo.proteusthemes.com/webmarket/shop/posters/premium-quality-2/">
    	    			    <img width="60" height="60" src="https://demo.proteusthemes.com/webmarket/wp-content/uploads/sites/5/2013/06/featured-2-260x260.png" class="attachment-shop_thumbnail wp-post-image" alt="featured-2">
        			    </a>				
    			    </div>
			    
    				<div class="desc">
    					<strong>
    						<a href="https://demo.proteusthemes.com/webmarket/shop/posters/premium-quality-2/">Premium Quality</a>					</strong>
    					<span class="light-clr qty">
    						Qty: 1						&nbsp;
    						<a href="https://demo.proteusthemes.com/webmarket/cart/?remove_item=d2ddea18f00665ce8623e36bd4e3c7c5&amp;_wpnonce=f2c04f8a44" class="fa fa-times-circle js-cart-item-remove" title="Remove this item"></a>					</span>
    				</div>
    				<div class="price">
    					<strong>
    						<span class="amount">$12.00</span>					</strong>
    				</div>
			    </div>
			    
			    <div class="item-in-cart clearfix">
				
    				<div class="image">
        				<a href="https://demo.proteusthemes.com/webmarket/shop/posters/premium-quality-2/">
    	    			    <img width="60" height="60" src="https://demo.proteusthemes.com/webmarket/wp-content/uploads/sites/5/2013/06/featured-2-260x260.png" class="attachment-shop_thumbnail wp-post-image" alt="featured-2">
        			    </a>				
    			    </div>
			    
    				<div class="desc">
    					<strong>
    						<a href="https://demo.proteusthemes.com/webmarket/shop/posters/premium-quality-2/">Premium Quality</a>					</strong>
    					<span class="light-clr qty">
    						Qty: 1						&nbsp;
    						<a href="https://demo.proteusthemes.com/webmarket/cart/?remove_item=d2ddea18f00665ce8623e36bd4e3c7c5&amp;_wpnonce=f2c04f8a44" class="fa fa-times-circle js-cart-item-remove" title="Remove this item"></a>					</span>
    				</div>
    				<div class="price">
    					<strong>
    						<span class="amount">$12.00</span>					</strong>
    				</div>
			    </div>
			    
            </div>
            
        </div>
        
        
        
    </div>
        
    </div>
</div>

<div class="clearfix"></div>