<div class="container">
    
    <ul class="root-categories">
        <li>
            <a href="">Home</a>
        </li>
        
        <li class="">
            <a href="">Fashion &nbsp; <i class="fa fa-chevron-down extra-small"></i></a>
            
            <div class="open-cat">
                
                <div class='opcwp col-md-12 extended'>
                    <?php for($i = 0 ; $i < 5 ; $i++) :?>
                
                    <div class="col-md-2 extended mb20">
                        <h4 class="mb15">Category</h4>
                        <ul class="subcategories">
                            <?php for($j = 0 ; $j < 5 ; $j++) :?>
                                <li><a href="">Subcategory</a></li>
                            <?php endfor;?>
                        </ul>
                    </div>
                    
                    <?php endfor; ?>    
                </div>
                
                
            </div>
            
        </li>
        
        <li>
            <a href="">Jewlery & Beauty &nbsp; <i class="fa fa-chevron-down extra-small"></i></a>
            
            <div class="open-cat">
                
                <div class='opcwp col-md-12 extended'>
                    <?php for($i = 0 ; $i < 5 ; $i++) :?>
                
                    <div class="col-md-2 extended mb20">
                        <h4 class="mb15">Category</h4>
                        <ul class="subcategories">
                            <?php for($j = 0 ; $j < 5 ; $j++) :?>
                                <li><a href="">Subcategory</a></li>
                            <?php endfor;?>
                        </ul>
                    </div>
                    
                    <?php endfor; ?>    
                </div>
                
                
            </div>
        </li>
        
        <li>
            <a href="">Deals & Special offers</a>
        </li>
        
    </ul>
    <div class="clearfix"></div>
</div>