<div class="col-md-12 col-sm-12 extended navig">
    
    <div class="col-md-8 col-sm-8">
        
        <ul class="main-nav">
            <li>
                <a href=""> Home </a>
            </li>

            <li class="relative dropdown">
                
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Shop &nbsp; <i class="fa fa-caret-down"></i>
                </a>
                
                 <ul class="dropdown-menu">
                    <li class="col-md-12 extended">
                        <a href="#">Link</a>
                        </li>
                    <li class="col-md-12 extended">
                        <a href="#opening">Link</a>
                    </li>
                </ul>            
            </li>
            
            <li>
                <a href="">
                     Blog &nbsp; <i class="fa fa-caret-down"></i>
                </a>
            </li>
            
            <li>
                <a href=""> 
                    Features &nbsp; <i class="fa fa-caret-down"></i>
                </a>
            </li>
            
            <li>
                <a href=""> About Us </a>
            </li>
            
            <li>
                <a href=""> Contact </a>
            </li>
            
        </ul>
        
        <form class="pull-right relative search-form" action="" method="GET">
            <input type="text" class="form-control">
            <button><i class="fa fa-search"></i></button>
        </form>
        
    </div>
        
    <div class="col-md-4 col-sm-4">
        cart & total & icon
    </div>
        
    </div>
</div>

<div class="clearfix"></div>