<div class="footer-top">
    <div class="container">
        <div class="row">
            
            <div class="col-md-3 col-sm-3">
                <h4 class="title_font">About Newyork Theme</h4>
                <p>NEWYORK is Premiun Prestashop Themes. It will be a great solution for online clothing, fashion and apparel store.</p>
            </div>
            
            <div class="col-md-2">
                
            </div>
            
            <div class="col-md-2">
                
            </div>
            
            <div class="col-md-2">
                
            </div>
            
            <div class="col-md-3">
                
            </div>
            
        </div>
    </div>
</div>

<div class="footer-bottom">
    <div class="container">
        <div class="row">
            
            <div class="footer-bottom-inner"></div>
            
        </div>
    </div>
</div>
