<div class="top-header-nav">
    
    <div class="container">
            
            <div class="row">
                
                <div class="col-sm-4">
                    <ul class="sctrl">
                        <li class="dropdown">
                            <a href="" data-toggle="dropdown">Romana <i class="fa fa-caret-down"></i></a>
                            <ul class="dropdown-menu">
                                 <li><a href="">Romana</a></li>
                                 <li><a href="">English</a></li>
                            </ul>
                        </li>
                        <li>
                            <a href="" data-toggle="dropdown">RON <i class="fa fa-caret-down"></i></a>
                            <ul class="dropdown-menu">
                                 <li><a href="">RON</a></li>
                                 <li><a href="">USD</a></li>
                                 <li><a href="">EUR</a></li>
                            </ul>
                        </li>
                    </ul>
                    
                </div>
                <div class="col-sm-4 text-center">
                    <p style="margin : 0 ; margin-top : 7px;">Welcome to DICKBUTT</p>
                </div>
                <div class="col-sm-4 text-right">
                    <ul class="sctrl">
                        <li>
                            <a href=""> <i class="fa fa-user"></i> Account</a>
                        </li>
                        <li>
                            <a href=""> <i class="fa fa-user"></i> My Cart</a>
                        </li>
                        <li>
                            <a href=""> <i class="fa fa-lock"></i> Login</a>
                        </li>
                    </ul>    
                </div>
                
            </div>
            
    </div>
    <div class="clearfix"></div>
</div>

<div class="middle-header-nav">
    <div class="container">
            
            <div class="row text-center">
                
                <div class="col-md-3"></div>
                
                <div class="col-md-6">
                    
                    <div class="logo-wp">
                        <a href="" class="logo">
                            <img src="http://demo.fieldthemes.com/newyork/home4/img/newyork-logo-1432971360.jpg" alt="site logo">
                        </a>
                    </div>
                    
                </div>
                
                <div class="col-md-3"></div>
                
                <!--<p style="line-height : 31px">THIS IS WHERE MIDDLE HEADER WILL BE</p>-->
            </div>
            
    </div>
</div>

<div class="header-menu-wp">
    <div class="container">
            
            <div class="row">
                
                <div class="col-sm-12">
                    
                    <ul class="nav nav-bar inline">
                        
                        <li>
                            <a href=""><i class="fa fa-home"></i></a>
                        </li>
                        <?php foreach($this->categories as $category) :  ?>
                        <?php if($category->getStatus() != \Application\Response\Status::ACTIVE) continue; ?>
                        <li>
                            <a href="" data-toggle="dropdown" 
                                data-target="<?php echo md5($category->getSlug());?>">
                                <?php echo $category->getTitle()?> 
                                <i class="fa fa-angle-down"></i>
                            </a>
                            <div class="menu-cat-wp dropdown-menu" id="<?php echo md5($category->getSlug());?>">
                                <?php foreach($category->getChildren() as $chdCategory) : ?>
                                <?php if($chdCategory->getStatus() != \Application\Response\Status::ACTIVE ) continue;?>
                                <div class="col-sm-3 mc-wp">
                                    <h4 class=''><?php echo $chdCategory->getTitle() ?></h4>
                                    
                                    <ul>
                                        <?php foreach($chdCategory->getChildren() as $chd) :?>
                                        <?php if($chd->getStatus() != \Application\Response\Status::ACTIVE ) continue;?>
                                        <li> 
                                            <a href="<?php echo $this->url('category', array('slug' => $chd->getSlug(), 'lang' => $this->lang))?>"><?php echo $chd->getTitle();?></a>
                                        </li>
                                        <?php endforeach;?>
                                        
                                    </ul>
                                </div>
                                <?php endforeach;?>
                                
                            </div>
                        </li>
                        <?php endforeach;?>
                        <!--<li>
                            <a href="">Man <i class="fa fa-angle-down"></i></a>
                        </li>
                        <li>
                            <a href="">Fashioon <i class="fa fa-angle-down"></i></a>
                        </li>
                        <li>
                            <a href="">Our Brand</a>
                        </li>-->
                        
                    </ul>
                    
                </div>
                
            </div>
            
    </div>
    <div class="header-menu-shadow"></div>
    <div class="clearfix"></div>
</div>
<!-- END TOP HEADER -->

<pre class="hide">
    <?php var_dump($this->categories)?>
    
</pre>