<meta name="viewport" content="width=device-width">

<?php 

echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); 

echo $this->headLink(
        array('rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon', 
            'href' => $this->basePath() . '/assets/img/favicon.ico'
            ))
        ->appendStylesheet($this->basePath() . '/assets/css/main.css')
        
        ->prependStylesheet($this->basePath() . '/assets/css/adds/bootstrap/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/assets/css/adds/font-awesome/font-awesome.min.css');
?>
      