<div class="hdrtop col-md-12 extended">
    <div class="col-md-3">
        <div class="col-md-12 extended">
            <a href="">Login / Register</a>
        </div>
    </div>
    
    <div class="col-md-9">
        <div class="col-md-12 extended text-right">
            <a href="">My account</a> &nbsp; | &nbsp;
            <a href="">Checkout</a>  &nbsp; | &nbsp;
            <a href="">Cart (0)</a>
        </div>
    </div>
</div>

<div class="hdrbtm col-md-12 extended">
    
    <div class="col-md-4 col-sm-4">
        <img src="<?php echo $this->basePath() ?>/assets/img/logo_.png" alt="<?php echo $this->translate('Utopia - Dev')?>">
    </div>
    
    <div class="col-md-8 col-sm8">
        <div class="col-md-8 col-sm-8 col-md-offset-4 text-right extended mt40 hidden-xs">
            
            <a href="">
                <i class="fa fa-facebook-official large"></i>
            </a>
             &nbsp;&nbsp;&nbsp;&nbsp;
            <a href="">
                <i class="fa fa-twitter large"></i>
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <a href="">
                <i class="fa fa-google-plus large"></i>
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <a href="">
                <i class="fa fa-pinterest-p large"></i>
            </a>
            
        </div>
    </div>
    
</div>

<div class="clearfix"></div>