<!--<div id="fb-root"></div>-->
<!--<script>(function(d, s, id) {-->
<!--  var js, fjs = d.getElementsByTagName(s)[0];-->
<!--  if (d.getElementById(id)) return;-->
<!--  js = d.createElement(s); js.id = id;-->
<!--  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.4&appId=526264897418151";-->
<!--  fjs.parentNode.insertBefore(js, fjs);-->
<!--}(document, 'script', 'facebook-jssdk'));</script>-->

<div id="TpHd" class="">
    <div class="container">
        <div class="col-xs-12 col-sm-6 extended">
            <ul>
                <li><a href="<?php echo $this->url('home');?>">Home</a></li>
                <!--<li class="dropdown">-->
                <!--    <a class="dropdown-toggle" data-toggle="dropdown" href="#change-colors">Change Colors</a>-->

                <!--    <ul class="dropdown-menu" role="menu">-->
                <!--        <li role="presentation"><a role="menuitem" class="changecolor green-text" tabindex="-1" href="#" title="Green color">Green</a></li>-->
                <!--        <li role="presentation"><a role="menuitem" class="changecolor blue-text" tabindex="-1" href="#" title="Blue color">Blue</a></li>-->
                <!--        <li role="presentation"><a role="menuitem" class="changecolor red-text" tabindex="-1" href="#" title="Red color">Red</a></li>-->
                <!--        <li role="presentation"><a role="menuitem" class="changecolor orange-text" tabindex="-1" href="#" title="Orange color">Orange</a></li>-->
                <!--        <li role="presentation"><a role="menuitem" class="changecolor navy-text" tabindex="-1" href="#" title="Navy color">Navy</a></li>-->
                <!--        <li role="presentation"><a role="menuitem" class="changecolor dark-green-text" tabindex="-1" href="#" title="Darkgreen color">Dark Green</a></li>-->
                <!--    </ul>-->
                <!--</li>-->
                <li><a href="index.php?page=blog">Blog</a></li>
                <li><a href="index.php?page=faq">FAQ</a></li>
                <li><a href="index.php?page=contact">Contact</a></li>
                <!--<li class="dropdown">-->
                <!--    <a class="dropdown-toggle" data-toggle="dropdown" href="#pages" aria-expanded="false">Pages</a>-->
                <!--    <ul class="dropdown-menu" role="menu">-->
                <!--        <li><a href="index.php?page=home&amp;style=alt2">Home</a></li>-->
                <!--        <li><a href="index.php?page=home-2&amp;style=alt2">Home Alt</a></li>-->
                <!--    </ul>-->
                <!--</li>-->
            </ul>
        </div>

        <div class="col-xs-12 col-sm-6 extended">
            <ul class="pull-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#change-language" aria-expanded="false">English</a>
                    <ul class="dropdown-menu" role="menu">
                        <li role="presentation">
                            <a role="menuitem" tabindex="-1" href="<?php echo $this->url('application', array('lang' => 'ro' , 'controller' => 'index' , 'action' => 'chLang')); ?>">Romana</a>
                        </li>
                        <li role="presentation">
                            <a role="menuitem" tabindex="-1" href="#">English</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#change-currency" aria-expanded="false">Dollar (US)</a>
                    <ul class="dropdown-menu" role="menu">
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Euro (EU)</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Dollar (US)</a></li>
                        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Leu(RON)</a></li>
                    </ul>
                </li>
                <li>
                    <a href="<?php echo $this->basePath('user/register'); ?>">Register</a>
                </li>
                <li>
                    <a href="<?php echo $this->basePath('user/login'); ?>">Login</a>
                </li>
            </ul>
        </div>
    </div>
</div>

<div id="LwHd" class="">
    <div class="container">

        <div class="col-md-3">
            <div class="logo">
                <a href="http://transvelo.in/demo/html/index.php?page=home">
                    <img alt="logo" src="<?php echo $this->basePath() . '/assets/img/logo__.png' ?>" height="54"/>
                </a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="contact-row">
                <div class="phone inline">
                    <i class="fa fa-phone"></i> (+800) 123 456 7890
                </div>
                <div class="contact inline">
                    <i class="fa fa-envelope"></i> contact@<span class="le-color">oursupport.com</span>
                </div>
            </div>
            <div class="search-area">
                <form>
                    <div class="control-group">
                        <input class="search-field" placeholder="Search for item">

                        <ul class="categories-filter animate-dropdown">
                            <li class="dropdown">

                                <a class="dropdown-toggle" data-toggle="dropdown" href="index.php?page=category-grid" aria-expanded="false">all categories</a>

                                <ul class="dropdown-menu" role="menu">
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="index.php?page=category-grid">laptops</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="index.php?page=category-grid">tv &amp; audio</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="index.php?page=category-grid">gadgets</a></li>
                                    <li role="presentation"><a role="menuitem" tabindex="-1" href="index.php?page=category-grid">cameras</a></li>

                                </ul>
                            </li>
                        </ul>

                        <a class="search-button" href="#"></a>    

                    </div>
                </form>
            </div>
        </div>

        <div class="col-md-3 cart-container extended ">

            <div class="col-md-4 extended">
                <a href=""><i class="fa fa-heart-o"></i> Wishlist</a>
            </div>
            <div class="col-md-8 extended">

                <div class="col-md-3 extended">
                    <img src="<?php echo $this->basePath(); ?>/assets/img/icon-cart.png" alt="" />
                    <span class="hide">3</span>
                </div>
                
                <div class="col-md-8">
                    
                    <ul class="animate-dropdown">
                        <li class="dropdown">

                            <a class="dropdown-toggle" id="CartDropdown" data-toggle="dropdown" href="" aria-expanded="false">
                                <span>Total price</span>
                                <span class="total-price">
                                    <span class="sign">$</span><span class="value">3219,00</span>
                                </span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                
                                <li role="presentation">
                                    
                                    <div id="TpCrt">
                                        
                                        <ul>
                                            <?php for( $pr = 0 ; $pr < 3 ; $pr++):?>
                                            <li>
                                                <div class="basket-item">
                                                    <div class="row">
                                                        <div class="col-xs-4 col-sm-4 no-margin text-center">
                                                            <div class="thumb">
                                                                <img alt="" src="<?php echo $this->basePath('assets/img/product-01.jpg');?>">
                                                            </div>
                                                        </div>
                                                        <div class="col-xs-8 col-sm-8 no-margin">
                                                            <div class="title">Blueberry</div>
                                                            <div class="price"><strong>$270.00</strong></div>
                                                        </div>
                                                    </div>
                                                    <a class="close-btn" href="#"></a>
                                                </div>
                                            </li>
                                            <?php endfor;?>
                                            <li class="checkout">
                                                <div class="basket-item">
                                                    <div class="row">
                                                        <div class="col-xs-12 col-sm-6">
                                                            <a href="index.php?page=cart" class="btn btn-default">View cart</a>
                                                        </div>
                                                        <div class="col-xs-12 col-sm-6">
                                                            <a href="index.php?page=checkout" class="btn btn-danger bold">Checkout</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </li>
                                        </ul>
                                        
                                    </div>
                                
                                </li>

                            </ul>
                        </li>
                    </ul>
                    
                </div>



            </div>


        </div>

    </div>
</div>
