<meta name="viewport" content="width=device-width">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
<?php 

echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge'); 

echo $this->headLink(
        array('rel' => 'shortcut icon',
            'type' => 'image/vnd.microsoft.icon', 
            'href' => $this->basePath() . '/assets/img/favicon.ico'
            ))
        ->appendStylesheet($this->basePath() . '/assets/css/main.css')
        ->appendStylesheet($this->basePath() . '/assets/css/general.css')
        ->prependStylesheet($this->basePath() . '/assets/css/adds/bootstrap/bootstrap.min.css')
        ->prependStylesheet($this->basePath() . '/assets/css/adds/font-awesome/font-awesome.min.css');
        


$this->headScript()
        ->prependFile($this->basePath() . '/assets/js/main.js')
        ->prependFile($this->basePath() . '/assets/js/adds/bootstrap/bootstrap.min.js')
        ->prependFile($this->basePath() . '/assets/js/adds/jquery/jquery-2.1.1.min.js')
    ;
?>
      