<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->partial('layout/head.phtml')?>
        <?php echo $this->headScript(); ?>

    </head>

    <body>
        
        <header class="container-fluid">

            <?php echo $this->render('layout/header.phtml')?>    
            
        </header>
        

        <main class="container-fluid">
            
                <?php echo $this->content; ?>    
            
        </main>
    
        <footer class="container-fluid">
           
            <?php echo $this->partial('layout/footer.phtml')?>
          
        </footer>
        
        <?php echo $this->render('layout/scripts.phtml')?>
        <?php echo $this->inlineScript();?>
        
    </body>
</html>