<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->partial('layout/head.phtml')?>
        <?php echo $this->headScript(); ?>

    </head>

    <body>
        
        <header class="hdr">

            <?php echo $this->render('layout/header.phtml')?>
            
        </header>

        <main data-role="main" class="main">
            
             
            <?php echo $this->content; ?>
            
            <div class="clearfix"></div>
            
        </main>
    
        <footer class="ftr">
           
            <?php echo $this->partial('layout/footer.phtml')?>
          
        </footer>
        
        <?php echo $this->render('layout/scripts.phtml')?>
        <?php echo $this->inlineScript();?>
        
    </body>
</html>