<?php

// $this->inlineScript()
//         ->prependFile($this->basePath() . '/assets/js/main.js')
//         ->prependFile($this->basePath() . '/assets/js/adds/bootstrap/bootstrap.min.js')
//         ->prependFile($this->basePath() . '/assets/js/adds/jquery/jquery-2.1.1.min.js')
//     ;
?>

<!-- <script type="text/javascript">
  window.___gcfg = {lang: 'en-GB'};

  (function() {
    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
    po.src = 'https://apis.google.com/js/platform.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
  })();
</script> -->