
<div class="col-md-12 extended">
    
    <div id="carousel" class="carousliderwp">
        <!-- WILL BE MOVED TO SOME HELPER! along with javascript intialization ! -->
        <img src="https://demo.proteusthemes.com/webmarket/wp-content/uploads/sites/5/2013/12/xslide3.jpg.pagespeed.ic.-CQrHva-eb.webp" />
        <img src="https://demo.proteusthemes.com/webmarket/wp-content/uploads/sites/5/2013/12/xslide.jpg.pagespeed.ic.8Ynf8xCxyf.webp" />
        <img src="https://demo.proteusthemes.com/webmarket/wp-content/uploads/sites/5/2013/12/xslide1.jpg.pagespeed.ic.-tNRWE6b-H.webp"  />
    
    </div>
    
    
</div>

<div class="clearfix"></div>

<div class="container-fluid">
    
    <div class="col-md-12 push-up over-sld">
        
        <div class="col-md-4">
            
            <div class="col-md-12 extended offer">
                <a href="">
                    <span class="title"><span class="light">Summer</span> Sale</span>
                    <em>up to 60% off on all shoes</em>
                </a>
            </div>
                
        </div>
        
        <div class="col-md-4">
            
            <div class="col-md-12 hot extended offer">
                <a href="">
                    <span class="title"><span class="light">Summer</span> Sale</span>
                    <em>up to 60% off on all shoes</em>
                </a>
            </div>
                
        </div>
        
        <div class="col-md-4">
            
            <div class="col-md-12 extended offer">
                <a href="">
                    <span class="title"><span class="light">Summer</span> Sale</span>
                    <em>up to 60% off on all shoes</em>
                </a>
            </div>
                
        </div>
        
        
    </div>
    
</div>

<div class="container-fluid">
    
    <div class="col-md-12">
        <h4 class="col-md-12">Featured Products</h4>
        
        <div class="col-md-12 pcw extended pcw-1">
            
            <?php for($i = 1 ; $i < 40 ; $i++) : ?>
            <div class="col-md-4 prwp">
                <section class="col-md-12 pr">
                    
                    <div class="col-md-12 extended pri">
                        <img src="https://demo.proteusthemes.com/webmarket/wp-content/uploads/sites/5/2013/06/260x260xfeatured-2-260x260.png.pagespeed.ic.m-bKCUquGf.webp" alt="product name">
                    </div>

                    <div class="col-md-12 extended prp">
                        
                        <h4 class="title">
                            <del><small class="amount">$15.00</small></del>
                            <strong class="amount">$12.00</strong>
                        </h4>
                        <strong class="no-margin">Premium Quality</strong>
                        
                    </div>
                    
                    <div class="prd">
                        <p class="no-margin">
                            59% Cotton Lorem Ipsum Dolor Sit Amet esed ultrices sapien nunc nam frignila
                        </p>
                    </div>
                    
                </section>
            </div>
            <?php endfor;?>
            
        </div>
        
    </div>
    
    
    
</div>




<?php 

$this->headLink()->appendStylesheet($this->basePath() . '/assets/css/pages/app.index.css');

$this->inlineScript()->prependFile($this->basePath() . '/assets/js/adds/caroufredsel/jquery.carouFredSel-6.2.1-packed.js');

$this->inlineScript()->appendFile($this->basePath() . '/assets/js/modules/application/module.js');


$this->inlineScript()->appendScript(        <<<START
    $().ready(function(){
       application.application.startCarouselFreadSlider(); 
    });
START
);
?>