<!-- APP INDEX FILE -->
<div class="">
    <div class="" style="height:400px;overflow : hidden">
        <img src="<?php echo $this->basePath('images/slider_bkg_look.jpg')?>" width="100%">
    </div>
    <div class="col-xs-12 mt25 mb25">
        
            
            <?php for($i = 0 ; $i < 4 ; $i++) :?>
            <div class="col-sm-3 col-xs-6">
                <div class="ci-cont">
                    
                    <div class="_ops">
                    
                    </div>
                    
                    <img width="100%" src="<?php echo $this->basePath('images/accessories_img_banner.jpg');?>" alt="category" />
                    
                </div>
            </div>
            <?php endfor;?>

        
    </div>
    
    <div class="clearfix"></div>
        
</div>

<div class="container-fluid product-wp">
    <!--<div class="container">-->
        <?php echo $this->partial('application/helper/products.phtml' , array()) ?>
    <!--</div>-->
</div>

<div class="container-fluid product-wp">
    <!--<div class="container">-->
        <?php echo $this->partial('application/helper/products.phtml' , array()) ?>
    <!--</div>-->
</div>