<?php
// Generated by Zend Framework 2
return array(
    'Mail\Module'                       => __DIR__ . '/Module.php',
    'PHPMailer'                           => __DIR__ . '/src/PHPMailer/class.phpmailer.php',
    'phpmailerException'                  => __DIR__ . '/src/PHPMailer/class.phpmailer.php',
    'POP3'                                => __DIR__ . '/src/PHPMailer/class.pop3.php',
    'SMTP'                                => __DIR__ . '/src/PHPMailer/class.smtp.php',
    'html2text'                           => __DIR__ . '/src/PHPMailer/extras/class.html2text.php',
    'ntlm_sasl_client_class'              => __DIR__ . '/src/PHPMailer/extras/ntlm_sasl_client.php',
);